import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { ReactNode } from "react";

import { GameContextProvider } from "@/components/game-context-provider";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <GameContextProvider>{children}</GameContextProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
